version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bi-app
    image: bi-app:latest
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
       - ./:/app
       - ./supervisor/conf.d/:/etc/supervisor/conf.d
